=== Développeur Java chez IT-CE
****
icon:calendar[] _Septembre 2013 à Octobre 2014_

icon:users[] http://www.it-ce.fr[IT-CE]

Dans le cadre de la mutualisation des SI entre le Crédit Foncier et la Caisse d'Epargne, participation au portage de l'application OGREC et à son intégration dans le nouveau SI.

* Projet OGREC -- Outil de Gestion de la Relation Client
** Fonctionnement en méthode agile (SCRUM)
** Etude de l’existant (Base de données / Moteur attribution)
** Modélisation du nouveau modèle de données
** Développement en Java du moteur d’attribution
** Développement de Webservices SOAP
** Développement de Batchs
** Configuration des serveurs d’application Websphere
** Rédaction de documentations techniques en vue de l’installation des applications sur les différents environnements (Recette utilisateur, Qualification, Production)

icon:gears[] Environnement Technique

** Langages

*** Java 6

** Frameworks -- Librairies

*** Spring WS, Spring IOC, Spring Data, Spring Batch

** Outils

*** Maven, TFS, Power AMC, Artifactory

** Environnement de développement

*** Eclipse, Windows

** Base de données

*** Oracle

** Serveurs

*** Tomcat, Websphere

_Mots Clés_ : Scrum, Spring Batch, Webservices SOAP

****
